= Common
:source-highlighter: highlight.js
:highlightjs-languages: asm


This is a core utility library for C64lib. It is written in KickAssembler but in general it contains only the code that is portable and can be used with other architectures based on MOS 6502 (such as VIC 20, C128, 8-bit Atari etc).

== common.asm

=== neg

=== incArgument

=== Far jumps

A set of macros that are handy if we are not sure if at given moment a near jump is feasible, or a "far conditional jump" trick should be used.

fbmi:: Far `bmi` branch. Depending on the effective jump distance it uses either `bmi` or `bpl`/`beq`/`jmp` combination.
fbne:: Far `bne` branch. Depending on the effective jump distance it uses either `bne` or `beq`/`jmp` trick.


== invoke.asm

Helper macros for implementing subroutines. These macros basically handle parameter passing via the stack which are then stored in dedicated memory (usually allocated in unused part of the subroutine). This technique is especially handy in case the overall size of the input data cannot be realistically passed via CPU registers. Recursive calls to the subroutines are not supported.

Parameters should be pushed onto the stack just before calling subroutine (which is done via `jsr` instruction). Within the subroutine, parameters must be fetched from the stack in reverse order and stored elsewhere. Before this is done, a return pointer must be preserved in order to enable return from the subroutine (a `rts` instruction). There are two macros devoted to this operation: `invokeStackBegin` and `invokeStackEnd`. These are actually combined with `pullParam` and `pushParam`.

[source,asm]
--
pushParamW()
pushParamW()
jsr subroutine

// ...

rotateMemRight: {

  invokeStackBegin(returnPtr)
  pullParamWList(List().add(loadFirst, loadNext, staNext, staLast))

  lda loadFirst:$ffff, x
  sta preserve
  loop:
    dex
    lda loadNext:$ffff, x
    inx
    sta staNext:$ffff, x
    dex
  bne loop
  lda preserve
  sta staLast:$ffff

  invokeStackEnd(returnPtr)
  rts
  // local vars
  returnPtr:      .word 0
  preserve:       .byte 0
}
--

== math.asm

== mem.asm