= c64lib - User's Manual
:icons: font
:toc: left
:docinfo:
:sectnums:
:stylesheet: clean.css
:source-highlighter: highlight.js
:highlightjs-languages: assembly
:kickass-version: 5.23
:rbt-version: 1.5.1
:c64lib-version: 0.3.0

WARNING: This document is under development!

The `c64lib` is a set of Kick Assembler macros grouped in several libraries.
They are the building blocks that can be reused in retro projects.
The intention behind `c64lib` is to provide retro community with modern development tools such as build support, CI assistance, dependency management, artifact versioning and comprehensive documentation.

The `c64lib` is hosted on GitHub: https://github.com/c64lib/.


include::10_overview.adoc[leveloffset=+1]

include::20_install.adoc[leveloffset=+1]

include::30_building_blocks.adoc[leveloffset=+1]

include::40_functional_guidelines.adoc[leveloffset=+1]

include::50_copper_64.adoc[leveloffset=+1]

include::70_contribute.adoc[leveloffset=+1]

include::80_reference.adoc[leveloffset=+1]

== Privacy disclaimer

=== How do we process your data

This website is powered by AsciiDoctor and is hosted on GitHub/GitHub Pages.

AsciiDoctor is not collecting or processing user data in any form.

GitHub however, as any other hosting company, can have full insight in visitor data, like connecting IP addresses, visited pages, etc.
Note that Github is not known to actively profile visitors.
By using a VPN you can (try to) prevent this.

=== Google Analytics

This website uses Google Analytics.
This happens only if you accept third party cookies.
I have configured Google Analytics so that IP addresses are anonymized.

Use the following option to grant or revoke collecting data and using cookies.

++++
<p>
<input type="checkbox" id="enableGA"> Enable Google Analytics
</p>
++++
