version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout
      - run: bundle update --bundler
      - run: bundle
      - run: bundle exec asciidoctor manual.adoc -D out
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/setup-github.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
