version: 2
jobs:
  deploy:
    docker:
      - image: circleci/jruby:latest
#      - image: circleci/ruby:3.0.0
    steps:
      - run: sudo apt install graphviz
      - checkout
      - run: bundle install
      - run: bash ./build.sh
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/setup-github.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
